---
title: "SV-seminaire  : Microsimulations"
author: admin
date: 2023-10-23
categories: ["Beamm"]
tags: ["Beamm","Microsimulation"]
---

# Digital resurrection! 

Le lundi 23 octobre 2023, Statistiek Vlaanderen organisait un séminaire sur les microsimulations. La microsimulation est une technique qui permet de modéliser les changements futurs dans des phénomènes sociaux complexes basés sur le comportement d'unités individuelles, telles que les individus et les ménages.

En plus d'une introduction sur les microsimulations en tant que technique de modélisation, des experts de l'intérieur et de l'extérieur du réseau de Statistics Flanders présenteront quelques exemples concrets de modèles de microsimulation pertinents pour la politique. J'ai participé à ce séminaire avec un exposé conjoint avec Tom Truyts :

    BEAMM-model (UCLouvain Saint-Louis): Un modèle de microsimulation en ligne et en libre accès pour les taxes, les cotisations sociales et les allocations.
    BEAMM-model: Tom Truyts et Hugues Annoye (UCLouvain Saint-Louis)